scaffold-eth/OP-RetroPGF3-Discovery-Voting

packages/nextjs/components/Header.tsx, packages/nextjs/components/lists/Card.tsx, packages/nextjs/components/op/btn/CustomProjectButton.tsx, packages/nextjs/components/op/input/OPInput.tsx, packages/nextjs/components/op/modals/AddListToBallotModal.tsx, packages/nextjs/components/op/modals/AlreadyOnBallotConflictModal.tsx, packages/nextjs/components/op/modals/EditDistributionModal.tsx, packages/nextjs/components/op/modals/LoadingModal.tsx, packages/nextjs/components/op/projects/ProjectList.tsx, packages/nextjs/components/op/projects/ProjectListCard.tsx, packages/nextjs/components/op/projects/ProjectListCardEditable.tsx, packages/nextjs/pages/list.tsx, packages/nextjs/styles/globals.css, packages/nextjs/tailwind.config.js
I reworked some of the components from a functionality perspective and added the edit distribution modal. Needs a second pass to enable the full functionality but the design is there.
=> rework components and add edit distribution modal

packages/nextjs/components/lists/SharedProjects.tsx, packages/nextjs/components/op/modals/AddListToBallotModal.tsx, packages/nextjs/components/op/modals/VoteModal.tsx, packages/nextjs/components/op/projects/ProjectList.tsx, packages/nextjs/components/op/projects/ProjectListCard.tsx, packages/nextjs/components/op/projects/ProjectListCardEditable.tsx, packages/nextjs/components/project/ProjectHeader.tsx, packages/nextjs/components/projects/Card.tsx
Add ballot in list page now follows the flow in the design
=> add ballot in list page

packages/nextjs/components/ballot/Ballot.tsx, packages/nextjs/components/lists/AllLists.tsx, packages/nextjs/components/lists/Card.tsx, packages/nextjs/components/lists/SharedProjects.tsx, packages/nextjs/components/op/btn/CustomProjectButton.tsx, packages/nextjs/components/op/modals/VoteModal.tsx, packages/nextjs/components/project/ProjectHeader.tsx, packages/nextjs/pages/lists.tsx, packages/nextjs/styles/globals.css
=> List page UI

packages/nextjs/pages/index.tsx
=> useRouter for redirect

packages/nextjs/styles/globals.css
=> Background color adjusted

packages/nextjs/components/op/modals/EditDistributionModal.tsx
=> edit modal input fixed

packages/nextjs/components/op/modals/VoteModal.tsx, packages/nextjs/components/project/ProjectHeader.tsx
=> add to ballot fixed

packages/nextjs/components/ballot/Ballot.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
I have modified some UI changes on the header, to look moderate over alignment with color changes.
=> UI changes

packages/nextjs/components/op/modals/VoteModal.tsx, packages/nextjs/components/project/ProjectHeader.tsx, packages/nextjs/pages/lists/[listId].tsx
=> button closes after edit is done

packages/nextjs/components/ballot/Ballot.tsx, packages/nextjs/tailwind.config.js
Changed the button width settings and darkmode defaults to correct the overflowing badge.
Closes https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/issues/66
=> Fix issue #66

packages/nextjs/components/projects/Card.tsx
Card now has border. Also adjusted border-radius on banner and card to match designs more closely.
Closes https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/issues/68
=> Issue #68 Resolution

packages/nextjs/components/projects/AllProjects.tsx, packages/nextjs/pages/lists.tsx, packages/nextjs/pages/projects.tsx
Fixes the "jumping" when switching between projects page and lists page.
Closes https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/issues/70
=> Fixes Issue #70

packages/nextjs/components/ballot/Ballot.tsx
Removed modal, "View Ballot" button in the header component links to /view-ballot page now
- [ x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
_Closes #48 _
Your ENS/address: milespatterson.eth
=> View ballot button links to page now, no more modal

packages/nextjs/components/op/modals/VoteModal.tsx, packages/nextjs/components/project/ProjectHeader.tsx
Uses a native dropdown for the ellipses menu with more predictable behaviour. Also the add to ballot button changes its appearance after you have added a ballot - per the designs.
Also, the ellipses menu dropdown only shows "edit distribution" when the project has been added.
=> Native dropdown for ellipses menu and add ballot button state change

packages/nextjs/components/lists/AllLists.tsx, packages/nextjs/components/lists/Card.tsx, packages/nextjs/components/lists/ListHeader.tsx, packages/nextjs/components/lists/SharedProjects.tsx, packages/nextjs/components/project/ProjectHeader.tsx, packages/nextjs/components/projects/AllProjects.tsx, packages/nextjs/components/shared/SuggestProjects.tsx, packages/nextjs/styles/globals.css, packages/nextjs/tailwind.config.js
mobile responsiveness
Before
After
=> Mobile res

packages/nextjs/components/op/modals/VoteModal.tsx, packages/nextjs/components/project/ProjectHeader.tsx
1. Fixed allocation issues described in issue #82 by modifying handleAllocationChange() function.
2. Fixed open/close toggle for dropdown to select between 'edit distribution', 'share', and 'report' on project details page.
_Closes #82  _
Your ENS/address: dannithomx.eth
=> Fixed Allocation issues

packages/nextjs/components/project/ProjectHeader.tsx
=> OP Allocated Link

packages/nextjs/components/Header.tsx, packages/nextjs/components/SwitchTheme.tsx, packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton.tsx
Dark theme button icon fixed
Before
After
=> dark button icon fixed

packages/nextjs/components/lists/ListHeader.tsx
=> Implementing Toggle Filter Functionality

packages/nextjs/components/ballot/AllBallots.tsx, packages/nextjs/components/projects/Card.tsx, packages/nextjs/pages/_app.tsx, packages/nextjs/pages/lists.tsx, packages/nextjs/pages/lists/[listId].tsx, packages/nextjs/pages/my-ballot.tsx, packages/nextjs/pages/projects.tsx, packages/nextjs/pages/projects/[projectId].tsx
Added share button and submit button to view ballot and also changed the background colors to white
=> added submit button and share button

packages/nextjs/components/projects/Card.tsx
=> added border to grid display of projects

packages/nextjs/components/lists/Card.tsx, packages/nextjs/components/lists/CreateList.tsx
Truncated the heading and description on the list card
After
=> truncate on list card

packages/nextjs/components/projects/Card.tsx, packages/nextjs/styles/globals.css
Updated the project image and icon to fit the design
After
=> project icon and image updated

packages/nextjs/components/ballot/AllBallots.tsx
Remove grid, list, and shuffle buttons from View Ballot page #128
1. Remove grid, list, and shuffle buttons from the View Ballot page
2. Remove the ProjectsPageHeader  component and add a title for “My ballot”
3. Refactor and remove unnecessary code for useEffect  and variables
4. Tested it and it worked okay. 
- [yes] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [yes] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
List View Issues 128
Your ENS/address: Coderxyz.eth
=> Remove grid, list, and shuffle buttons from View Ballot pag

packages/nextjs/components/op/modals/LoadingModal.tsx, packages/nextjs/components/op/modals/SuccessModal.tsx
Small adjustment to the Loading and Success modals to update font color to work in both light and dark mode.
Fixes #134
=> Font color adjustment in dark mode modals

packages/nextjs/components/ballot/AllBallots.tsx, packages/nextjs/components/project/ProjectHeader.tsx
1. Add the correct banner and icon for projects
2. Conditionally rendering if the project has a banner or an icon it renders it otherwise we use predefined  images
3. Test it and it worked.
- [yes] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [yes] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
List View Issues 129
Your ENS/address: Coderxyz.eth
=> Project views need the project image and icon

packages/nextjs/components/lists/Card.tsx, packages/nextjs/local_database/seedDb.ts, packages/nextjs/models/Project.ts, packages/nextjs/next.config.js, packages/nextjs/pages/api/suggestedProjects.ts, packages/nextjs/pages/projects/[projectId].tsx
Adjusts the query to get the project.
_Closes #142 _
=> Resolves issue 142 where projects don't load

packages/nextjs/components/projects/Card.tsx
Added Link elements to the row view for projects and also added extra ones to the grid view to expand the clickable area to include the banner and such.
_Closes https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/issues/140 _
=> project row view is clickable

.husky/pre-commit, packages/nextjs/components/SearchProjects.tsx, packages/nextjs/components/ballot/AllBallots.tsx, packages/nextjs/components/lists/CreateList.tsx, packages/nextjs/components/op/modals/AddListToBallotModal.tsx, packages/nextjs/components/op/modals/AlreadyOnBallotConflictModal.tsx, packages/nextjs/components/op/modals/EditDistributionModal.tsx, packages/nextjs/components/op/modals/VoteModal.tsx, packages/nextjs/components/op/projects/ProjectListCard.tsx, packages/nextjs/components/op/projects/ProjectListCardEditable.tsx, packages/nextjs/components/projects/Card.tsx, packages/nextjs/components/shared/ProjectRowEditable.tsx, packages/nextjs/components/shared/SuggestProjects.tsx, packages/nextjs/context/BallotContext.tsx, packages/nextjs/types/list.ts, packages/nextjs/utils/isAddedToBallot.ts
This should make it so we can use the preview builds again.
=> Fixes linting

packages/nextjs/components/lists/Card.tsx, packages/nextjs/components/lists/Pagination.tsx, packages/nextjs/components/projects/AllProjects.tsx, packages/nextjs/components/projects/Card.tsx, packages/nextjs/pages/projects/[projectId].tsx, packages/nextjs/styles/globals.css
Updated the pagination and removed overlap, Removed underscores from categories on cards and pages
#144 #145 #139 
=> Use real data

packages/nextjs/components/lists/ListsPageHeader.tsx, packages/nextjs/components/projects/Card.tsx, packages/nextjs/components/projects/ProjectsPageHeader.tsx
In the project horizontal view, added a small border to the icons and made them square.
=> Square project logo and add border

packages/nextjs/utils/populateListProjects.ts
Fixes projects icon on shared list (i.e the list part of issue #163)
Your ENS/address: dannithomx.eth
=> Fixed projects icon on shared list

packages/nextjs/components/projects/Card.tsx
The icons no longer shrink #167 
=> shrinked project icons fixed

packages/nextjs/components/lists/AllLists.tsx, packages/nextjs/components/lists/Card.tsx, packages/nextjs/components/projects/AllProjects.tsx, packages/nextjs/components/projects/Card.tsx, packages/nextjs/styles/globals.css
Fix List and Project page and made them responsive with several changes
1.  Truncated list and projects page for long titles and descriptions
2. Add conditional rendering for column view 
3. Test it and it worked.
- [yes] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [yes] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
List View Issues #133
Your ENS/address: Coderxyz.eth
=> Truncated list and projects page

packages/nextjs/components/lists/CreateList.tsx
List creation requirements #161
1. Add front-end validations for CreateList Form Component
2. Add validate form function, which checks if the list name and description are valid
3. Add conditional rendering for the list name & description. If they are not valid it displays a helpful message
4. Test it and it worked.
- [yes] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [yes] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)
List View Issues 161
Your ENS/address: Coderxyz.eth
=> Add front-end validations for List creation requirements component
